import { ILeaderBoardDto } from 'src/app/models/leaderBoard';

export const LEADERBOARD_DATA: ILeaderBoardDto[] = [
  {
    wwcd: 'intermediate',
    finishes: 'synergy',
    positionPoints: 36,
    damage: 'Virtual',
    headShots: 19,
    suvTime: 'Quality-focused',
    totalPoints: 21,
  },
  {
    wwcd: 'instruction set',
    finishes: 'clear-thinking',
    positionPoints: 34,
    damage: 'background',
    headShots: 93,
    suvTime: 'budgetary management',
    totalPoints: 91,
  },
  {
    wwcd: 'analyzer',
    finishes: 'client-driven',
    positionPoints: 67,
    damage: 'zero defect',
    headShots: 34,
    suvTime: 'contextually-based',
    totalPoints: 18,
  },
  {
    wwcd: 'local area network',
    finishes: 'solution',
    positionPoints: 26,
    damage: 'Horizontal',
    headShots: 81,
    suvTime: 'matrix',
    totalPoints: 8,
  },
  {
    wwcd: 'Extended',
    finishes: 'encryption',
    positionPoints: 83,
    damage: 'Object-based',
    headShots: 76,
    suvTime: 'Managed',
    totalPoints: 88,
  },
  {
    wwcd: 'directional',
    finishes: 'internet solution',
    positionPoints: 83,
    damage: 'local',
    headShots: 10,
    suvTime: 'bottom-line',
    totalPoints: 35,
  },
  {
    wwcd: 'grid-enabled',
    finishes: 'service-desk',
    positionPoints: 83,
    damage: 'collaboration',
    headShots: 23,
    suvTime: 'Diverse',
    totalPoints: 9,
  },
  {
    wwcd: 'migration',
    finishes: 'discrete',
    positionPoints: 27,
    damage: 'mobile',
    headShots: 79,
    suvTime: 'system engine',
    totalPoints: 49,
  },
  {
    wwcd: 'migration',
    finishes: 'cohesive',
    positionPoints: 76,
    damage: 'Reduced',
    headShots: 87,
    suvTime: 'Enterprise-wide',
    totalPoints: 37,
  },
  {
    wwcd: 'Organic',
    finishes: 'Multi-tiered',
    positionPoints: 24,
    damage: 'Synchronised',
    headShots: 42,
    suvTime: 'Diverse',
    totalPoints: 72,
  },
  {
    wwcd: 'Robust',
    finishes: 'access',
    positionPoints: 98,
    damage: 'grid-enabled',
    headShots: 84,
    suvTime: 'Re-engineered',
    totalPoints: 9,
  },
  {
    wwcd: 'attitude-oriented',
    finishes: 'multi-tasking',
    positionPoints: 8,
    damage: 'object-oriented',
    headShots: 1,
    suvTime: 'composite',
    totalPoints: 3,
  },
  {
    wwcd: 'Open-architected',
    finishes: 'Compatible',
    positionPoints: 33,
    damage: 'scalable',
    headShots: 5,
    suvTime: 'stable',
    totalPoints: 48,
  },
  {
    wwcd: 'implementation',
    finishes: 'demand-driven',
    positionPoints: 13,
    damage: 'Graphic Interface',
    headShots: 67,
    suvTime: 'support',
    totalPoints: 31,
  },
  {
    wwcd: 'architecture',
    finishes: 'encompassing',
    positionPoints: 47,
    damage: 'Organized',
    headShots: 73,
    suvTime: 'intermediate',
    totalPoints: 84,
  },
  {
    wwcd: 'web-enabled',
    finishes: 'bifurcated',
    positionPoints: 24,
    damage: 'Enterprise-wide',
    headShots: 57,
    suvTime: 'leading edge',
    totalPoints: 41,
  },
  {
    wwcd: 'Mandatory',
    finishes: 'disintermediate',
    positionPoints: 64,
    damage: 'national',
    headShots: 26,
    suvTime: 'local',
    totalPoints: 3,
  },
  {
    wwcd: 'exuding',
    finishes: 'orchestration',
    positionPoints: 88,
    damage: 'contingency',
    headShots: 96,
    suvTime: 'methodical',
    totalPoints: 6,
  },
  {
    wwcd: 'Proactive',
    finishes: 'Integrated',
    positionPoints: 60,
    damage: 'Expanded',
    headShots: 56,
    suvTime: 'knowledge user',
    totalPoints: 72,
  },
  {
    wwcd: 'Persistent',
    finishes: 'upward-trending',
    positionPoints: 26,
    damage: 'radical',
    headShots: 20,
    suvTime: 'Seamless',
    totalPoints: 19,
  },
  {
    wwcd: 'didactic',
    finishes: 'collaboration',
    positionPoints: 70,
    damage: 'analyzing',
    headShots: 33,
    suvTime: 'Innovative',
    totalPoints: 13,
  },
  {
    wwcd: 'info-mediaries',
    finishes: 'concept',
    positionPoints: 6,
    damage: 'Operative',
    headShots: 97,
    suvTime: 'Expanded',
    totalPoints: 62,
  },
  {
    wwcd: 'Innovative',
    finishes: 'archive',
    positionPoints: 51,
    damage: 'Balanced',
    headShots: 51,
    suvTime: 'Extended',
    totalPoints: 80,
  },
  {
    wwcd: 'Optional',
    finishes: 'Decentralized',
    positionPoints: 37,
    damage: 'homogeneous',
    headShots: 78,
    suvTime: 'Realigned',
    totalPoints: 77,
  },
  {
    wwcd: 'reciprocal',
    finishes: 'Triple-buffered',
    positionPoints: 93,
    damage: 'implementation',
    headShots: 52,
    suvTime: 'Business-focused',
    totalPoints: 64,
  },
  {
    wwcd: 'needs-based',
    finishes: 'Universal',
    positionPoints: 1,
    damage: 'demand-driven',
    headShots: 43,
    suvTime: 'Synergistic',
    totalPoints: 17,
  },
  {
    wwcd: 'analyzer',
    finishes: 'analyzing',
    positionPoints: 24,
    damage: 'Compatible',
    headShots: 9,
    suvTime: 'complexity',
    totalPoints: 29,
  },
  {
    wwcd: 'Innovative',
    finishes: 'De-engineered',
    positionPoints: 13,
    damage: 'Innovative',
    headShots: 96,
    suvTime: 'Phased',
    totalPoints: 83,
  },
  {
    wwcd: 'upward-trending',
    finishes: 'matrices',
    positionPoints: 35,
    damage: 'zero tolerance',
    headShots: 80,
    suvTime: 'Networked',
    totalPoints: 53,
  },
  {
    wwcd: 'pricing structure',
    finishes: 'conglomeration',
    positionPoints: 2,
    damage: 'middleware',
    headShots: 60,
    suvTime: 'website',
    totalPoints: 37,
  },
  {
    wwcd: 'process improvement',
    finishes: 'collaboration',
    positionPoints: 2,
    damage: 'client-driven',
    headShots: 91,
    suvTime: 'internet solution',
    totalPoints: 53,
  },
  {
    wwcd: 'Sharable',
    finishes: 'groupware',
    positionPoints: 97,
    damage: 'access',
    headShots: 48,
    suvTime: 'executive',
    totalPoints: 91,
  },
  {
    wwcd: 'project',
    finishes: 'Multi-layered',
    positionPoints: 9,
    damage: 'foreground',
    headShots: 95,
    suvTime: 'benchmark',
    totalPoints: 82,
  },
  {
    wwcd: 'instruction set',
    finishes: 'intermediate',
    positionPoints: 68,
    damage: 'Cloned',
    headShots: 98,
    suvTime: 'content-based',
    totalPoints: 74,
  },
  {
    wwcd: 'Distributed',
    finishes: 'clear-thinking',
    positionPoints: 95,
    damage: 'core',
    headShots: 96,
    suvTime: 'protocol',
    totalPoints: 5,
  },
  {
    wwcd: 'success',
    finishes: 'strategy',
    positionPoints: 77,
    damage: 'Organized',
    headShots: 28,
    suvTime: 'instruction set',
    totalPoints: 89,
  },
  {
    wwcd: '6th generation',
    finishes: 'Exclusive',
    positionPoints: 82,
    damage: 'concept',
    headShots: 54,
    suvTime: 'Open-architected',
    totalPoints: 20,
  },
  {
    wwcd: 'secured line',
    finishes: 'info-mediaries',
    positionPoints: 98,
    damage: 'productivity',
    headShots: 7,
    suvTime: 'Secured',
    totalPoints: 77,
  },
  {
    wwcd: 'Re-engineered',
    finishes: 'foreground',
    positionPoints: 33,
    damage: 'non-volatile',
    headShots: 88,
    suvTime: 'adapter',
    totalPoints: 50,
  },
  {
    wwcd: 'middleware',
    finishes: 'asynchronous',
    positionPoints: 100,
    damage: 'interactive',
    headShots: 25,
    suvTime: 'well-modulated',
    totalPoints: 20,
  },
  {
    wwcd: 'moderator',
    finishes: 'paradigm',
    positionPoints: 99,
    damage: 'algorithm',
    headShots: 39,
    suvTime: 'intranet',
    totalPoints: 54,
  },
  {
    wwcd: 'Upgradable',
    finishes: 'Synchronised',
    positionPoints: 50,
    damage: 'Polarised',
    headShots: 7,
    suvTime: 'Devolved',
    totalPoints: 7,
  },
  {
    wwcd: 'interactive',
    finishes: 'moderator',
    positionPoints: 53,
    damage: 'Focused',
    headShots: 81,
    suvTime: 'mission-critical',
    totalPoints: 55,
  },
  {
    wwcd: 'dedicated',
    finishes: 'standardization',
    positionPoints: 13,
    damage: '6th generation',
    headShots: 52,
    suvTime: 'Profit-focused',
    totalPoints: 44,
  },
  {
    wwcd: 'architecture',
    finishes: 'regional',
    positionPoints: 59,
    damage: 'Mandatory',
    headShots: 51,
    suvTime: 'dynamic',
    totalPoints: 41,
  },
  {
    wwcd: 'User-friendly',
    finishes: 'framework',
    positionPoints: 73,
    damage: 'local',
    headShots: 73,
    suvTime: 'support',
    totalPoints: 45,
  },
  {
    wwcd: 'Configurable',
    finishes: 'multi-state',
    positionPoints: 12,
    damage: 'heuristic',
    headShots: 30,
    suvTime: 'tertiary',
    totalPoints: 23,
  },
  {
    wwcd: 'workforce',
    finishes: 'Polarised',
    positionPoints: 12,
    damage: 'incremental',
    headShots: 68,
    suvTime: 'Enterprise-wide',
    totalPoints: 38,
  },
  {
    wwcd: 'context-sensitive',
    finishes: 'optimal',
    positionPoints: 1,
    damage: 'Public-key',
    headShots: 3,
    suvTime: 'Cross-platform',
    totalPoints: 51,
  },
  {
    wwcd: 'Open-source',
    finishes: 'Adaptive',
    positionPoints: 38,
    damage: 'Reactive',
    headShots: 90,
    suvTime: 'bottom-line',
    totalPoints: 76,
  },
  {
    wwcd: 'application',
    finishes: 'content-based',
    positionPoints: 86,
    damage: 'Virtual',
    headShots: 70,
    suvTime: 'matrix',
    totalPoints: 68,
  },
  {
    wwcd: 'secured line',
    finishes: 'Seamless',
    positionPoints: 73,
    damage: 'Optional',
    headShots: 20,
    suvTime: 'monitoring',
    totalPoints: 97,
  },
  {
    wwcd: 'architecture',
    finishes: 'Virtual',
    positionPoints: 71,
    damage: 'tertiary',
    headShots: 65,
    suvTime: 'Versatile',
    totalPoints: 1,
  },
  {
    wwcd: 'archive',
    finishes: 'Intuitive',
    positionPoints: 63,
    damage: 'bottom-line',
    headShots: 33,
    suvTime: 'toolset',
    totalPoints: 39,
  },
  {
    wwcd: 'user-facing',
    finishes: 'Re-contextualized',
    positionPoints: 28,
    damage: 'attitude',
    headShots: 25,
    suvTime: 'Compatible',
    totalPoints: 52,
  },
  {
    wwcd: 'Programmable',
    finishes: 'Organized',
    positionPoints: 64,
    damage: 'Customizable',
    headShots: 20,
    suvTime: 'high-level',
    totalPoints: 29,
  },
  {
    wwcd: 'bottom-line',
    finishes: 'background',
    positionPoints: 67,
    damage: 'access',
    headShots: 76,
    suvTime: 'Visionary',
    totalPoints: 22,
  },
  {
    wwcd: 'Sharable',
    finishes: 'systemic',
    positionPoints: 59,
    damage: 'conglomeration',
    headShots: 5,
    suvTime: 'holistic',
    totalPoints: 61,
  },
  {
    wwcd: 'intermediate',
    finishes: 'Virtual',
    positionPoints: 78,
    damage: 'foreground',
    headShots: 44,
    suvTime: 'Customizable',
    totalPoints: 57,
  },
  {
    wwcd: 'tertiary',
    finishes: 'firmware',
    positionPoints: 43,
    damage: 'radical',
    headShots: 51,
    suvTime: 'didactic',
    totalPoints: 23,
  },
  {
    wwcd: 'Distributed',
    finishes: 'User-friendly',
    positionPoints: 34,
    damage: 'Customer-focused',
    headShots: 44,
    suvTime: 'Reduced',
    totalPoints: 3,
  },
  {
    wwcd: 'Progressive',
    finishes: '24/7',
    positionPoints: 13,
    damage: 'Multi-tiered',
    headShots: 41,
    suvTime: 'Switchable',
    totalPoints: 51,
  },
  {
    wwcd: 'asynchronous',
    finishes: 'productivity',
    positionPoints: 39,
    damage: 'open architecture',
    headShots: 11,
    suvTime: 'bottom-line',
    totalPoints: 27,
  },
  {
    wwcd: 'grid-enabled',
    finishes: 'modular',
    positionPoints: 56,
    damage: 'zero tolerance',
    headShots: 84,
    suvTime: 'Fundamental',
    totalPoints: 47,
  },
  {
    wwcd: 'moderator',
    finishes: 'approach',
    positionPoints: 9,
    damage: 'holistic',
    headShots: 27,
    suvTime: 'optimal',
    totalPoints: 37,
  },
  {
    wwcd: 'Total',
    finishes: 'encompassing',
    positionPoints: 15,
    damage: 'open architecture',
    headShots: 96,
    suvTime: 'Programmable',
    totalPoints: 54,
  },
  {
    wwcd: 'installation',
    finishes: 'demand-driven',
    positionPoints: 74,
    damage: 'Persevering',
    headShots: 2,
    suvTime: 'Robust',
    totalPoints: 79,
  },
  {
    wwcd: 'real-time',
    finishes: 'bottom-line',
    positionPoints: 42,
    damage: 'Multi-lateral',
    headShots: 2,
    suvTime: 'access',
    totalPoints: 73,
  },
  {
    wwcd: '4th generation',
    finishes: 'Triple-buffered',
    positionPoints: 90,
    damage: 'functionalities',
    headShots: 44,
    suvTime: 'circuit',
    totalPoints: 87,
  },
  {
    wwcd: 'Innovative',
    finishes: 'Horizontal',
    positionPoints: 15,
    damage: 'heuristic',
    headShots: 95,
    suvTime: 'software',
    totalPoints: 49,
  },
  {
    wwcd: 'protocol',
    finishes: 'help-desk',
    positionPoints: 42,
    damage: 'zero tolerance',
    headShots: 90,
    suvTime: 'toolset',
    totalPoints: 40,
  },
  {
    wwcd: 'optimal',
    finishes: 'access',
    positionPoints: 93,
    damage: 'Face to face',
    headShots: 18,
    suvTime: 'regional',
    totalPoints: 36,
  },
  {
    wwcd: 'conglomeration',
    finishes: 'Implemented',
    positionPoints: 1,
    damage: 'web-enabled',
    headShots: 88,
    suvTime: 'Open-architected',
    totalPoints: 87,
  },
  {
    wwcd: 'Monitored',
    finishes: 'fault-tolerant',
    positionPoints: 89,
    damage: 'instruction set',
    headShots: 14,
    suvTime: 'project',
    totalPoints: 23,
  },
  {
    wwcd: 'open system',
    finishes: 'frame',
    positionPoints: 46,
    damage: 'Quality-focused',
    headShots: 79,
    suvTime: 'ability',
    totalPoints: 1,
  },
  {
    wwcd: 'model',
    finishes: 'ability',
    positionPoints: 34,
    damage: 'Profound',
    headShots: 67,
    suvTime: 'Optional',
    totalPoints: 65,
  },
  {
    wwcd: 'dynamic',
    finishes: 'heuristic',
    positionPoints: 75,
    damage: 'definition',
    headShots: 71,
    suvTime: 'regional',
    totalPoints: 35,
  },
  {
    wwcd: 'Inverse',
    finishes: 'transitional',
    positionPoints: 60,
    damage: 'Adaptive',
    headShots: 63,
    suvTime: 'Face to face',
    totalPoints: 86,
  },
  {
    wwcd: 'function',
    finishes: 'interface',
    positionPoints: 13,
    damage: 'architecture',
    headShots: 17,
    suvTime: 'Balanced',
    totalPoints: 68,
  },
  {
    wwcd: 'emulation',
    finishes: 'system-worthy',
    positionPoints: 77,
    damage: 'human-resource',
    headShots: 64,
    suvTime: 'explicit',
    totalPoints: 52,
  },
  {
    wwcd: 'solution-oriented',
    finishes: 'background',
    positionPoints: 89,
    damage: 'internet solution',
    headShots: 90,
    suvTime: 'composite',
    totalPoints: 8,
  },
  {
    wwcd: '24/7',
    finishes: 'Synergized',
    positionPoints: 38,
    damage: 'context-sensitive',
    headShots: 95,
    suvTime: 'global',
    totalPoints: 44,
  },
  {
    wwcd: 'archive',
    finishes: 'impactful',
    positionPoints: 95,
    damage: 'middleware',
    headShots: 86,
    suvTime: 'application',
    totalPoints: 92,
  },
  {
    wwcd: 'web-enabled',
    finishes: 'Innovative',
    positionPoints: 5,
    damage: 'mission-critical',
    headShots: 54,
    suvTime: 'Graphic Interface',
    totalPoints: 40,
  },
  {
    wwcd: 'object-oriented',
    finishes: 'Diverse',
    positionPoints: 92,
    damage: 'leading edge',
    headShots: 49,
    suvTime: 'product',
    totalPoints: 84,
  },
  {
    wwcd: 'object-oriented',
    finishes: 'functionalities',
    positionPoints: 22,
    damage: 'maximized',
    headShots: 67,
    suvTime: 'model',
    totalPoints: 3,
  },
  {
    wwcd: 'Reactive',
    finishes: 'didactic',
    positionPoints: 52,
    damage: 'productivity',
    headShots: 56,
    suvTime: 'help-desk',
    totalPoints: 39,
  },
  {
    wwcd: 'radical',
    finishes: 'Persevering',
    positionPoints: 46,
    damage: 'function',
    headShots: 6,
    suvTime: 'mobile',
    totalPoints: 27,
  },
  {
    wwcd: 'dedicated',
    finishes: 'high-level',
    positionPoints: 78,
    damage: 'analyzer',
    headShots: 10,
    suvTime: 'composite',
    totalPoints: 90,
  },
  {
    wwcd: 'Graphical User Interface',
    finishes: 'Visionary',
    positionPoints: 9,
    damage: 'Vision-oriented',
    headShots: 70,
    suvTime: 'local area network',
    totalPoints: 26,
  },
  {
    wwcd: 'Reverse-engineered',
    finishes: 'Adaptive',
    positionPoints: 31,
    damage: 'help-desk',
    headShots: 11,
    suvTime: 'challenge',
    totalPoints: 11,
  },
  {
    wwcd: 'standardization',
    finishes: 'Cloned',
    positionPoints: 79,
    damage: 'real-time',
    headShots: 5,
    suvTime: 'utilisation',
    totalPoints: 94,
  },
  {
    wwcd: 'Progressive',
    finishes: 'value-added',
    positionPoints: 72,
    damage: 'focus group',
    headShots: 87,
    suvTime: 'support',
    totalPoints: 41,
  },
  {
    wwcd: 'responsive',
    finishes: 'Fundamental',
    positionPoints: 34,
    damage: 'Multi-channelled',
    headShots: 83,
    suvTime: 'optimal',
    totalPoints: 36,
  },
  {
    wwcd: 'systematic',
    finishes: 'directional',
    positionPoints: 18,
    damage: 'attitude-oriented',
    headShots: 10,
    suvTime: 'grid-enabled',
    totalPoints: 58,
  },
  {
    wwcd: 'object-oriented',
    finishes: 'solution',
    positionPoints: 9,
    damage: 'hardware',
    headShots: 2,
    suvTime: 'Triple-buffered',
    totalPoints: 78,
  },
  {
    wwcd: 'interface',
    finishes: 'regional',
    positionPoints: 61,
    damage: 'capacity',
    headShots: 55,
    suvTime: 'Synergized',
    totalPoints: 97,
  },
  {
    wwcd: 'multimedia',
    finishes: 'uniform',
    positionPoints: 6,
    damage: 'Robust',
    headShots: 86,
    suvTime: 'object-oriented',
    totalPoints: 59,
  },
  {
    wwcd: 'Up-sized',
    finishes: 'directional',
    positionPoints: 35,
    damage: 'Proactive',
    headShots: 56,
    suvTime: 'Graphical User Interface',
    totalPoints: 38,
  },
  {
    wwcd: 'dedicated',
    finishes: 'uniform',
    positionPoints: 18,
    damage: 'Persevering',
    headShots: 5,
    suvTime: 'multimedia',
    totalPoints: 51,
  },
];
